blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/Tell-Me-Mo/tellmemo-app/discussions
    about: Ask questions or start discussions about the project
  - name: Security Issue
    url: https://github.com/Tell-Me-Mo/tellmemo-app/security/advisories/new
    about: Report a security vulnerability privately