name: Feature Request
description: Suggest a new feature
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: What feature would you like to see?
      placeholder: I'd like to be able to...
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this useful?
      placeholder: This would help with...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      placeholder: Mockups, examples, or links
    validations:
      required: false
