// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKRXhR8Zyrj1hToqzTpNMh4r1BdcnCqO0',
    appId: '1:341249025817:web:689c7af59c6ed25e1b0788',
    messagingSenderId: '341249025817',
    projectId: 'tellmemo-6dfa2',
    authDomain: 'tellmemo-6dfa2.firebaseapp.com',
    storageBucket: 'tellmemo-6dfa2.firebasestorage.app',
    measurementId: 'G-9JP1NDY787',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpuYhJhvAB31sChN_9s0jNhXnFwS3rFrg',
    appId: '1:341249025817:ios:79f0ac783eae4a281b0788',
    messagingSenderId: '341249025817',
    projectId: 'tellmemo-6dfa2',
    storageBucket: 'tellmemo-6dfa2.firebasestorage.app',
    iosBundleId: 'com.visieasy.tellmemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpuYhJhvAB31sChN_9s0jNhXnFwS3rFrg',
    appId: '1:341249025817:ios:79f0ac783eae4a281b0788',
    messagingSenderId: '341249025817',
    projectId: 'tellmemo-6dfa2',
    storageBucket: 'tellmemo-6dfa2.firebasestorage.app',
    iosBundleId: 'com.visieasy.tellmemo',
  );
}
