"""Add enhanced analytics fields to summaries

Revision ID: 3a00877aedfb
Revises: 003_add_activities
Create Date: 2025-09-09 20:50:34.357088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a00877aedfb'
down_revision: Union[str, Sequence[str], None] = '003_add_activities'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('activities', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_activities_project_id'), table_name='activities')
    op.drop_index(op.f('idx_activities_timestamp'), table_name='activities')
    op.drop_index(op.f('idx_activities_type'), table_name='activities')
    op.add_column('summaries', sa.Column('sentiment_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('summaries', sa.Column('risks_and_blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('summaries', sa.Column('cross_meeting_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('summaries', sa.Column('priority_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('summaries', sa.Column('communication_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'communication_insights')
    op.drop_column('summaries', 'priority_scores')
    op.drop_column('summaries', 'cross_meeting_insights')
    op.drop_column('summaries', 'risks_and_blockers')
    op.drop_column('summaries', 'sentiment_analysis')
    op.create_index(op.f('idx_activities_type'), 'activities', ['type'], unique=False)
    op.create_index(op.f('idx_activities_timestamp'), 'activities', ['timestamp'], unique=False)
    op.create_index(op.f('idx_activities_project_id'), 'activities', ['project_id'], unique=False)
    op.alter_column('activities', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('activities', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###
