name: Frontend Tests

on:
  pull_request:
    branches: [main]
    paths:
      - 'lib/**'
      - 'test/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - '.github/workflows/frontend-tests.yml'
  push:
    branches: [main]
    paths:
      - 'lib/**'
      - 'test/**'
      - 'pubspec.yaml'

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info
          flags: frontend
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Check coverage threshold
        run: |
          # Install lcov for coverage parsing
          brew install lcov

          # Calculate coverage percentage
          COVERAGE=$(lcov --summary coverage/lcov.info 2>&1 | grep "lines" | awk '{print $2}' | sed 's/%//')
          echo "Coverage: ${COVERAGE}%"

          # Check if coverage meets minimum threshold (50%)
          if (( $(echo "$COVERAGE < 50" | bc -l) )); then
            echo "::warning::Coverage ${COVERAGE}% is below target threshold of 50%"
          fi

          # Target is 50-60%, so we show a warning but don't fail
          echo "::notice::Frontend test coverage: ${COVERAGE}% (target: 50-60%)"
