name: Frontend Docker Build

on:
  push:
    branches: [main, develop]
    paths:
      - 'lib/**'
      - 'web/**'
      - 'assets/**'
      - 'pubspec.yaml'
      - 'Dockerfile'
      - '.github/workflows/frontend-docker.yml'
  pull_request:
    branches: [main]
    paths:
      - 'lib/**'
      - 'web/**'
      - 'assets/**'
      - 'pubspec.yaml'

permissions:
  contents: write
  packages: write

env:
  IMAGE_NAME: tellmemo-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        run: |
          # Get the latest frontend tag or start at 0.0.0
          LATEST_TAG=$(git tag -l "frontend-v*" --sort=-v:refname | head -1 | sed 's/frontend-v//' || echo "0.0.0")

          # Increment patch version
          IFS='.' read -ra VER <<< "$LATEST_TAG"
          MAJOR=${VER[0]:-0}
          MINOR=${VER[1]:-0}
          PATCH=${VER[2]:-0}
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Building frontend version: $NEW_VERSION"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          # No build args needed - config is injected at runtime via docker-compose environment variables
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.ref == 'refs/heads/main' && 'latest' || 'develop' }}
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create git tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "frontend-v${{ steps.version.outputs.version }}" -m "Frontend release ${{ steps.version.outputs.version }}"
          git push origin "frontend-v${{ steps.version.outputs.version }}"

      - name: Create GitHub Release
        uses: actions/github-script@v7
        with:
          script: |
            const tagName = `frontend-v${{ steps.version.outputs.version }}`;
            const releaseName = `Frontend v${{ steps.version.outputs.version }}`;
            const branch = '${{ github.ref }}' === 'refs/heads/main' ? 'main' : 'develop';

            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tagName,
              name: releaseName,
              body: `## Frontend Release v${{ steps.version.outputs.version }}

            **Branch:** ${branch}
            **Commit:** ${{ github.sha }}

            ### Docker Images
            - \`${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}\`
            - \`${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${branch === 'main' ? 'latest' : 'develop'}\`
            - \`${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}\`

            ### Changes
            ${{ github.event.head_commit.message }}`,
              draft: false,
              prerelease: branch !== 'main'
            });